# Generated by Django 2.0.4 on 2018-04-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField()),
                ('postal_code', models.IntegerField()),
                ('locality', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='building',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.Company'),
        ),
    ]
