# Generated by Django 2.0.4 on 2018-04-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180410_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
